image:
  repository: ghcr.io/piscoaq/backend
  tag: main
  pullPolicy: Always

httpRoute:
  enabled: false

service:
  port: 5000

env:
  - name: MONGODB_URI
    valueFrom:
      secretKeyRef:
        name: mongodb-backend-credentials
        key: connectionString

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
